name: Build mod

on:
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: jcdcdev.Eco.ShelfLife
      PROJECT_PATH: ./src/jcdcdev.Eco.ShelfLife/jcdcdev.Eco.ShelfLife.csproj
      BUILD_OUTPUT: ./build-output
      MOD_OUTPUT: ./build-assets/Mods/jcdcdev.Eco.ShelfLife
      ASSET_NAME: jcdcdev.Eco.ShelfLife-dev-${{ github.sha }}
      ARTIFACT_OUTPUT: ./build-assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} -o ${{ env.MOD_OUTPUT }} --configuration Release 
      - uses: vimtor/action-zip@v1
        with:
          files: ${{ env.ARTIFACT_OUTPUT }}
          dest: ${{ env.ASSET_NAME }}.zip
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ASSET_NAME }}
          path: ${{ env.ASSET_NAME }}.zip
