name: Update modio mod description
on:
    workflow_dispatch:

jobs:
    update_mod_description:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Showdown
              run: npm install showdown -g
            - name: Convert README to HTML
              id: convert
              run: |
                sudo apt-get install pandoc
                pandoc .github/README.md -s -o README.html
                $README_HTML=(cat README.html)
                echo "README_HTML=$README_HTML" >> "$GITHUB_ENV"
            - name: Use README HTML
              run: |
                echo "The HTML of the README file is $README_HTML"
            - name: Update modio mod description
              run: |
                curl -X PUT 'https://api.mod.io/v1/games/${{ secrets.MODIO_GAME }}/mods/${{ secrets.MODIO_MOD }}' \
                -H 'Authorization: Bearer ${{ secrets.MODIO_TOKEN }}' \
                -d 'description=$README_HTML'
