name: Update modio mod description
on:
    workflow_dispatch:

jobs:
    update_mod_description:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Showdown
              run: npm install showdown -g
            - name: Convert README to HTML
              id: convert
              run: |
                sudo apt-get install pandoc
                README_HTML=$(pandoc .github/README.md -s -o README.html)
                echo "::set-output name=README_HTML::$README_HTML"
            - name: Use README HTML
              run: |
                echo "The HTML of the README file is ${{ steps.convert.outputs.README_HTML }}"
            # - name: Update modio mod description
            #   run: |
            #     curl -X PUT 'https://api.mod.io/v1/games/${{ secrets.MODIO_GAME }}/mods/${{ secrets.MODIO_MOD }}' \
            #     -H 'Authorization: Bearer ${{ secrets.MODIO_TOKEN }}' \
            #     --data-urlencode 'description@/dev/stdin' <<< "${{ steps.convert.outputs.README_HTML }}"}'
