name: Update modio mod description
on:
    workflow_dispatch:

jobs:
    update_mod_description:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Showdown
              run: npm install showdown -g
            - name: Convert README to HTML
              id: convert
              run: |
                html_content=$(showdown makehtml -i .github/README.md)
                echo "::set-output name=html_content::$html_content"
            - name: Update modio mod description
              run: |
                curl -X PUT 'https://api.mod.io/v1/games/${{ secrets.MODIO_GAME }}/mods/${{ secrets.MODIO_MOD }}' \
                -H 'Authorization: Bearer ${{ secrets.MODIO_TOKEN }}' \
                -d 'description=${{ steps.convert.outputs.html_content }}'
